# -*- coding: utf-8 -*-
"""My_first_tokenizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fac3zp7z0RzdP5Nw2IHPbIHqsUh112vh
"""

promt ="Who is PM of INdia?"

import tiktoken

tokenizer = tiktoken.encoding_for_model(model_name = "gpt-4o")

tokIds = tokenizer.encode(promt)

tokIds

resIds = [4827, 382, 19121, 7524, 30]

text = tokenizer.decode(resIds)

text